// Bundles the MCP bridge (src/mcp) into one self-contained CommonJS file that a
// plain `node` can run with no node_modules beside it.
//
// Why bundle rather than let tsc emit it:
//   1. @modelcontextprotocol/sdk publishes its subpaths through an "exports"
//      map, which the main project's classic `moduleResolution: "Node"` cannot
//      read. esbuild resolves exports maps correctly.
//   2. The SDK is ESM-only at the source level; bundling to CJS lets the bridge
//      run under a plain `node dist/mcp/stdio.js` invocation.
//   3. ow-electron-builder packs the app into an asar, which a plain `node`
//      cannot read. One flat file can be shipped as an extraResource instead.
//   4. It keeps the SDK and zod as devDependencies — bundled into this one
//      file, never installed beside the app. The Vantage app process itself
//      gains no new runtime dependency at all.
import { build, context } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const watch = process.argv.includes('--watch');

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(root, 'src', 'mcp', 'stdio.ts')],
  outfile: join(root, 'dist', 'mcp', 'stdio.js'),
  bundle: true,
  format: 'cjs',
  platform: 'node',
  // Electron 39 ships Node 22; a packaged run may also use the system node.
  target: 'node20',
  sourcemap: false,
  logLevel: 'info',
  legalComments: 'none',
  banner: {
    js: '// Vantage MCP bridge — generated by scripts/build-mcp.mjs. Do not edit.',
  },
};

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('[build-mcp] watching src/mcp…');
} else {
  await build(options);
  console.log('[build-mcp] done → dist/mcp/stdio.js');
}
